### PR TITLE
Automatic DN generation for creating accounts & groups using friendly name

### PR DESCRIPTION
**Pull request by sunnypav**
If userRDNAttribute and userCreateContainerDN are specified for creating
a user using friendly username UserDN will be computed as <User RDN
Attribute>=<username>,<userCreateContainerDN>. Same as for group need to
specify groupRDNAttribute and GroupCreateContainerDN. If RDN attribute
is specified alone and single base context is present DN will be
generated as <RDN attribute>=<value>, <single BASE DN>.

Specifying RDN attribute and having multiple base context and trying to
create a user using user friendly name results in error.

Please review and let me know for any changes

### CODE REVIEW

**Comment by ilgrosso** [comment]
Several issues to be addressed before merging:
 1. none of commit messages reference LDAP-20
 1. the new properties are designed (and commented in `Messages.properties`) for create only, but need to also work and be tested with update: everything, including property names needs to reflect this
 1. the new `LdapSchemaMapping#createLDAPName` method should better go in `LdapUtil` as the `quietCreateLdapName` method; effectively, it should be investigated whether the former can completely replace the latter

You can see an updated patch for this pull request (mainly for code formatting, please update your IDE, but also for messages) attached to LDAP-20.

**Comment by sunnypav** [comment]
Regarding update operation with these new properties

1) If the User RDN attribute is same as username attribute and trying to update the username using friendly name
       i) Should we rename the entry with the new DN generated same as in create (or)
      ii) Should we rename the entry with the updated RDN attribute
Second options seems to be good for me.

Let me know your opinion

**Comment by sunnypav** [comment]
where can i get the code formatter for this project ?

**Comment by ilgrosso** [comment]
Regarding your question above about update, I'd rather go for option (i), e.g. replicating what is done during create: this because the configuration parameters might have changed in the meanwhile and option (ii) could lead to wrong behavior.

**Comment by ilgrosso** [comment]
Closing as [LDAP-20](https://connid.atlassian.net/projects/LDAP/issues/LDAP-20) is now closed.

**Pull request closed without merging**
